export type WorkflowLane = "coding_repository" | "repo_hygiene" | "documentation_knowledge" | "memory" | "plugin_runtime" | "scheduling_cron" | "telegram_operator" | "deployment_release" | "unknown";
export type RiskClass = "safe_readonly" | "safe_validation" | "bounded_local_change" | "approval_required" | "forbidden" | "blocked";
export type WorkStatus = "queued" | "running" | "complete" | "partial" | "blocked" | "failed" | "awaiting_approval" | "paused_rate_limit";
export interface RecommendedAction { action: string; intent?: string; requiresApproval: boolean; readOnly: boolean; }
export interface AutonomousWorkItem { taskId: string; source: "operator" | "queue" | "standing_order" | "workboard" | "capability_gap" | "schedule"; requestedOutcome: string; workflowLane: WorkflowLane; riskClass: RiskClass; autonomyLevel: "read_only" | "bounded" | "approval_gated"; requiredEvidence: string[]; approvalState: "not_required" | "pending" | "approved" | "rejected"; status: WorkStatus; selectedTool: string | null; selectedWorker: string | null; nextSafeAction: RecommendedAction | null; idempotencyKey: string; createdAt: string; updatedAt: string; }
export interface ToolResult { handled: boolean; status: "success" | "failed" | "denied" | "unavailable" | "rate_limited"; changedState: boolean; safety: { readOnly: boolean }; evidenceLocation?: string | null; recommendedNextAction?: RecommendedAction | null; exitCode?: number | null; summary?: string; }
export interface InvocationLedgerEvent { taskId: string; timestamp: string; requestedTask: string; workflowLane: WorkflowLane; riskClass: RiskClass; selectedTool: string | null; source: "plugin" | "core" | "worker"; governedIntent: string; sanitizedArguments: Record<string, unknown>; resultStatus: ToolResult["status"]; exitCode: number | null; changedState: boolean; evidenceLocation: string | null; fallbackReason: string | null; recommendedNextAction: RecommendedAction | null; approvalRequired: boolean; continuationDecision: string; workerSessionId: string | null; }
export type CapabilityGapClass = "approval_required" | "missing_skill" | "missing_tool_or_plugin" | "missing_specialist_worker" | "memory_or_config_failure" | "provider_rate_limit" | "forbidden_action" | "unsupported_lane" | "validation_failure" | "runtime_transport_failure";
export interface CapabilityGap { gapId: string; boundaryClass: CapabilityGapClass; blockedTask: string; missingCapability: string; currentLimitation: string; workflowLane: WorkflowLane; riskLevel: RiskClass; occurrenceCount: number; firstSeen: string; lastSeen: string; evidenceReferences: string[]; proposedCapabilityType: "skill" | "tool" | "plugin" | "worker" | "policy" | "documentation" | "runtime repair"; suggestedImplementation: string; requiredApproval: boolean; validationPlan: string; recommendedPriority: "low" | "medium" | "high"; }
export interface ControllerCheckpoint { item: AutonomousWorkItem; stepCount: number; completedActions: string[]; repeatedFailures: number; events: InvocationLedgerEvent[]; gaps: CapabilityGap[]; }
